export const GET_MY_POST_REQUEST = "GET_MY_POST_REQUEST";
export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS";
export const GET_MY_POST_FAIL = "GET_MY_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAIL = "GET_ALL_POST_FAIL";

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL";
export const GET_SINGLE_POST_RESET = "GET_SINGLE_POST_RESET";

export const POST_LIKE_AND_UNLIKE_REQUEST = "POST_LIKE_AND_UNLIKE_REQUEST";
export const POST_LIKE_AND_UNLIKE_SUCCESS = "POST_LIKE_AND_UNLIKE_SUCCESS";
export const POST_LIKE_AND_UNLIKE_FAIL = "POST_LIKE_AND_UNLIKE_FAIL";
export const POST_LIKE_AND_UNLIKE_RESET = "POST_LIKE_AND_UNLIKE_RESET";
